version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - model
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=db

  model:
    build:
      context: .
    command: python code_analysis/model_server.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: code_complexity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
