# Generated by Django 5.1.6 on 2025-05-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javafile',
            name='cbo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
