# Generated by Django 5.1.5 on 2025-03-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_wcc', models.FloatField(default=0.0)),
                ('pie_chart_path', models.TextField(blank=True, null=True)),
                ('cbo', models.FloatField(default=0.0)),
                ('mpc', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ComplexityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('line_content', models.TextField()),
                ('size', models.IntegerField(default=0)),
                ('tokens', models.TextField()),
                ('control_structure_complexity', models.FloatField(default=0.0)),
                ('nesting_weight', models.FloatField(default=0.0)),
                ('inheritance_weight', models.FloatField(default=0.0)),
                ('compound_condition_weight', models.FloatField(default=0.0)),
                ('try_catch_weight', models.FloatField(default=0.0)),
                ('thread_weight', models.FloatField(default=0.0)),
                ('cbo_weight', models.FloatField(default=0.0)),
                ('total_complexity', models.FloatField(default=0.0)),
                ('java_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexities', to='Drinks.javafile')),
            ],
        ),
        migrations.CreateModel(
            name='CBOPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=255)),
                ('recommendations', models.TextField()),
                ('java_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbo_predictions', to='Drinks.javafile')),
            ],
        ),
        migrations.CreateModel(
            name='MethodComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=255)),
                ('total_complexity', models.FloatField(default=0.0)),
                ('category', models.CharField(max_length=50)),
                ('bar_chart', models.TextField(blank=True, null=True)),
                ('java_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_complexities', to='Drinks.javafile')),
            ],
        ),
    ]
