# Generated by Django 5.1.5 on 2025-03-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drinks', '0002_javafile_complexitydetail_cboprediction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='javafile',
            name='cbo',
        ),
        migrations.RemoveField(
            model_name='javafile',
            name='mpc',
        ),
        migrations.RemoveField(
            model_name='javafile',
            name='pie_chart_path',
        ),
    ]
