# Generated by Django 5.1.6 on 2025-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drinks', '0002_alter_javafile_cbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='csharpfile',
            name='cbo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csharpfile',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csharpfile',
            name='refactored_java_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
