# Generated by Django 5.1.5 on 2025-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drinks', '0003_remove_javafile_cbo_remove_javafile_mpc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexitydetail',
            name='java_file',
        ),
        migrations.RemoveField(
            model_name='methodcomplexity',
            name='java_file',
        ),
        migrations.AlterField(
            model_name='javafile',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='CBOPrediction',
        ),
        migrations.DeleteModel(
            name='ComplexityDetail',
        ),
        migrations.DeleteModel(
            name='MethodComplexity',
        ),
    ]
