# Generated by Django 5.1.6 on 2025-03-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drinks', '0004_remove_complexitydetail_java_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaFileComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('java_code', models.TextField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField()),
                ('control_structure_complexity', models.IntegerField()),
                ('nesting_weight', models.IntegerField()),
                ('inheritance_weight', models.IntegerField()),
                ('compound_condition_weight', models.IntegerField()),
                ('try_catch_weight', models.IntegerField()),
                ('thread_weight', models.IntegerField()),
                ('cbo', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='JavaFile',
        ),
    ]
