# Generated by Django 5.1.6 on 2025-03-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drinks', '0005_javafilecomplexity_delete_javafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('java_code', models.TextField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('total_wcc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MethodComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=255)),
                ('total_complexity', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50)),
                ('java_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='Drinks.javafile')),
            ],
        ),
        migrations.DeleteModel(
            name='JavaFileComplexity',
        ),
    ]
