# Generated by Django 5.1.6 on 2025-03-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drinks', '0006_javafile_methodcomplexity_delete_javafilecomplexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodcomplexity',
            name='cbo_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='methodcomplexity',
            name='compound_condition_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='methodcomplexity',
            name='control_structure_complexity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='methodcomplexity',
            name='inheritance_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='methodcomplexity',
            name='nesting_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='methodcomplexity',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='methodcomplexity',
            name='thread_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='methodcomplexity',
            name='try_catch_weight',
            field=models.IntegerField(default=0),
        ),
    ]
