# Generated by Django 5.1.6 on 2025-03-10 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drinks', '0007_methodcomplexity_cbo_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSharpFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('csharp_code', models.TextField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('total_wcc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CSharpMethodComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=255)),
                ('total_complexity', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('control_structure_complexity', models.IntegerField(default=0)),
                ('nesting_weight', models.IntegerField(default=0)),
                ('inheritance_weight', models.IntegerField(default=0)),
                ('compound_condition_weight', models.IntegerField(default=0)),
                ('try_catch_weight', models.IntegerField(default=0)),
                ('thread_weight', models.IntegerField(default=0)),
                ('cbo_weight', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50)),
                ('csharp_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='Drinks.csharpfile')),
            ],
        ),
    ]
