# Generated by Django 5.1.3 on 2025-03-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRefactoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_code', models.TextField()),
                ('refactored_code', models.TextField()),
                ('original_complexity', models.FloatField()),
                ('refactored_complexity', models.FloatField()),
                ('original_readability', models.FloatField()),
                ('refactored_readability', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignPatternResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(choices=[('Factory Method', 'Factory Method'), ('Singleton', 'Singleton'), ('Observer', 'Observer'), ('Decorator', 'Decorator'), ('Strategy', 'Strategy'), ('Adapter', 'Adapter'), ('Builder', 'Builder'), ('Prototype', 'Prototype')], max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('Creational', 'Creational'), ('Structural', 'Structural'), ('Behavioral', 'Behavioral')], max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('pattern', models.CharField(choices=[('Factory', 'Factory'), ('Strategy', 'Strategy'), ('Observer', 'Observer')], max_length=50)),
                ('rule', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
    ]
