# Generated by Django 5.1.7 on 2025-03-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_formatter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideline',
            name='pattern',
            field=models.CharField(choices=[('Factory', 'Factory'), ('Strategy', 'Strategy'), ('Observer', 'Observer'), ('AbstractFactory', 'Abstract Factory'), ('Builder', 'Builder Pattern'), ('Prototype', 'Prototype Pattern'), ('Singleton', 'Singleton Pattern'), ('Adapter', 'Adapter Pattern'), ('Bridge', 'Bridge Pattern'), ('Composite', 'Composite Pattern'), ('Decorator', 'Decorator Pattern'), ('Facade', 'Facade Pattern'), ('Flyweight', 'Flyweight Pattern'), ('Proxy', 'Proxy Pattern'), ('ChainOfResponsibility', 'Chain of Responsibility'), ('Command', 'Command Pattern'), ('Interpreter', 'Interpreter Pattern'), ('Iterator', 'Iterator Pattern'), ('Mediator', 'Mediator Pattern'), ('Memento', 'Memento Pattern'), ('State', 'State Pattern'), ('TemplateMethod', 'Template Method Pattern'), ('Visitor', 'Visitor Pattern')], max_length=50),
        ),
    ]
