# Generated by Django 5.1.6 on 2025-03-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_formatter', '0002_alter_guideline_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpatternresource',
            name='pattern_name',
            field=models.CharField(choices=[('Factory', 'Factory'), ('Singleton', 'Singleton'), ('Observer', 'Observer'), ('Decorator', 'Decorator'), ('Strategy', 'Strategy'), ('Adapter', 'Adapter'), ('Builder', 'Builder'), ('Prototype', 'Prototype')], max_length=100),
        ),
    ]
