# Generated by Django 4.2.16 on 2024-12-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility_checker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessibilityScore',
        ),
    ]
