# Generated by Django 4.2.19 on 2025-03-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_githubchallenge_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubchallenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='low', max_length=10),
        ),
    ]
