# Generated by Django 4.2.19 on 2025-03-07 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_gitgamescore_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitgamescore',
            name='github_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.githubchallenge'),
        ),
    ]
