# Generated by Django 5.1.6 on 2025-03-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gitgamescore_github_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitgamescore',
            name='critical_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gitgamescore',
            name='minor_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gitgamescore',
            name='moderate_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gitgamescore',
            name='serious_score',
            field=models.FloatField(default=0.0),
        ),
    ]
