# Generated by Django 4.2.20 on 2025-03-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gitgamescore_critical_score_gitgamescore_minor_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitgamescore',
            name='critical_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gitgamescore',
            name='minor_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gitgamescore',
            name='moderate_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gitgamescore',
            name='serious_score',
            field=models.FloatField(default=0.0),
        ),
    ]
