# Generated by Django 4.2.20 on 2025-03-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_gitgamescore_critical_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitgamescore',
            name='total_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gitgamescore',
            name='weighted_score',
            field=models.FloatField(default=0.0),
        ),
    ]
