# Generated by Django 4.2.20 on 2025-03-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_gitgamescore_total_violations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitgamescore',
            name='total_violations',
        ),
        migrations.RemoveField(
            model_name='gitgamescore',
            name='weighted_score',
        ),
    ]
