# Generated by Django 4.2.20 on 2025-03-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='badge_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
